'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GrblPanel.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 For more details on this app, please visit:  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AboutBox_AboutBox_Load_ForMoreDetailsOnThisAppPleaseVisit() As String
            Get
                Return ResourceManager.GetString("AboutBox_AboutBox_Load_ForMoreDetailsOnThisAppPleaseVisit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 GrblPanel is designed for use with Grbl 0.9G or later. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AboutBox_AboutBox_Load_GrblPanelIsDesignedForUseWithGrbl09GOrLater() As String
            Get
                Return ResourceManager.GetString("AboutBox_AboutBox_Load_GrblPanelIsDesignedForUseWithGrbl09GOrLater", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Connect 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Button_Connection_Text_Connect() As String
            Get
                Return ResourceManager.GetString("Button_Connection_Text_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Alarm lock  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_AlarmLock() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_AlarmLock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Arc radius error  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_ArcRadiusError() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_ArcRadiusError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Axis command conflict  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_AxisCommandConflict() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_AxisCommandConflict", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Axis words exist  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_AxisWordsExist() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_AxisWordsExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bad number format  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_BadNumberFormat() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_BadNumberFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Check door  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_CheckDoor() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_CheckDoor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Command value is not integer  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_CommandValueIsNotInteger() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_CommandValueIsNotInteger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 EEPROM read fail, using Defaults  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_EEPROMReadFailUsingDefaults() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_EEPROMReadFailUsingDefaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Expected command letter  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_ExpectedCommandLetter() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_ExpectedCommandLetter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 G43 dynamic axis error  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_G43DynamicAxisError() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_G43DynamicAxisError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 G53 invalid motion mode  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_G53InvalidMotionMode() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_G53InvalidMotionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Homing is not enabled  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_HomingIsNotEnabled() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_HomingIsNotEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid line number  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_InvalidLineNumber() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_InvalidLineNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid statement  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_InvalidStatement() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_InvalidStatement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid target  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_InvalidTarget() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_InvalidTarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Line overflow  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_LineOverflow() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_LineOverflow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Modal group violation  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_ModalGroupViolation() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_ModalGroupViolation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Line 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_New_Line() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_New_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No axis words  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_NoAxisWords() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_NoAxisWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No axis words in plane  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_NoAxisWordsInPlane() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_NoAxisWordsInPlane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No offsets in plane  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_NoOffsetsInPlane() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_NoOffsetsInPlane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Not idle  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_NotIdle() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_NotIdle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Setting disabled  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_SettingDisabled() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_SettingDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Step rate &gt; 30kHz  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_StepRate30kHz() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_StepRate30kHz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Undefined feed rate  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_UndefinedFeedRate() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_UndefinedFeedRate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unsupported command  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_UnsupportedCommand() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_UnsupportedCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unsupported coordinate system  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_UnsupportedCoordinateSystem() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_UnsupportedCoordinateSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unused words  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_UnusedWords() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_UnusedWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Value &lt; 0  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_Value0() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_Value0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Value &lt; 3 usec  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_Value3Usec() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_Value3Usec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Value word missing  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_ValueWordMissing() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_ValueWordMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Word repeated  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGcodeView_WordRepeated() As String
            Get
                Return ResourceManager.GetString("GrblGcodeView_WordRepeated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data Validation Error 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnAdd_Click_DataValidationError() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnAdd_Click_DataValidationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 You cannot create a macro without a name. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnAdd_Click_YouCannotCreateAMacroWithoutAName() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnAdd_Click_YouCannotCreateAMacroWithoutAName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 You need to add some G-code to save a macro 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnAdd_Click_YouNeedToAddSomeGCodeToSaveAMacro() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnAdd_Click_YouNeedToAddSomeGCodeToSaveAMacro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 And A Port Number In The Format 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_And_A_Port_Number_In_The_Format() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_And_A_Port_Number_In_The_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 and a port number in the format 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_AndAPortNumberInTheFormat() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_AndAPortNumberInTheFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Connect 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Connect() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Connect Error 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Connect_Error() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Connect_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Disconnect 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Disconnect() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Disconnected 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Disconnected() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 End 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_End() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_End", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Idle 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Idle() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Or Connect The Cable 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Or_Connect_The_Cable() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Or_Connect_The_Cable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 or connect the cable 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_OrConnectTheCable() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_OrConnectTheCable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please Enter An IP Address 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Please_Enter_An_IP_Address() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Please_Enter_An_IP_Address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please Select A Com Port 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_Please_Select_A_Com_Port() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_Please_Select_A_Com_Port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please enter an IP Address 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_PleaseEnterAnIPAddress() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_PleaseEnterAnIPAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please select a Com port 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnConnDisconnect_Click_PleaseSelectAComPort() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnConnDisconnect_Click_PleaseSelectAComPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure you want to delete the  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnDeleteMacro_Click_AreYouSureYouWantToDeleteThe() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnDeleteMacro_Click_AreYouSureYouWantToDeleteThe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Confirm Delete 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_btnDeleteMacro_Click_ConfirmDelete() As String
            Get
                Return ResourceManager.GetString("GrblGui_btnDeleteMacro_Click_ConfirmDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_dgMacros_DoubleClick_Update() As String
            Get
                Return ResourceManager.GetString("GrblGui_dgMacros_DoubleClick_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are You Certain That You Want To Close 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_grblgui_unload_Are_You_Certain_That_You_Want_To_Close() As String
            Get
                Return ResourceManager.GetString("GrblGui_grblgui_unload_Are_You_Certain_That_You_Want_To_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you certain that you want to close? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_grblgui_unload_AreYouCertainThatYouWantToClose() As String
            Get
                Return ResourceManager.GetString("GrblGui_grblgui_unload_AreYouCertainThatYouWantToClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure you want to exit without saving your Macro changes? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_GrblMacroButtons_FormClosing_AreYouSureYouWantToExitWithoutSavingYourMacroChanges() As String
            Get
                Return ResourceManager.GetString("GrblGui_GrblMacroButtons_FormClosing_AreYouSureYouWantToExitWithoutSavingYourMacr"& _ 
                        "oChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Confirm exit without saving. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_GrblMacroButtons_FormClosing_ConfirmExitWithoutSaving() As String
            Get
                Return ResourceManager.GetString("GrblGui_GrblMacroButtons_FormClosing_ConfirmExitWithoutSaving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_GrblMacroButtons_Load_Add() As String
            Get
                Return ResourceManager.GetString("GrblGui_GrblMacroButtons_Load_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CHECK 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_showGrblStatus_CHECK() As String
            Get
                Return ResourceManager.GetString("GrblGui_showGrblStatus_CHECK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 HOLD 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_showGrblStatus_HOLD() As String
            Get
                Return ResourceManager.GetString("GrblGui_showGrblStatus_HOLD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IDLE 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_showGrblStatus_IDLE() As String
            Get
                Return ResourceManager.GetString("GrblGui_showGrblStatus_IDLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resume 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_showGrblStatus_Resume() As String
            Get
                Return ResourceManager.GetString("GrblGui_showGrblStatus_Resume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RUN 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_showGrblStatus_RUN() As String
            Get
                Return ResourceManager.GetString("GrblGui_showGrblStatus_RUN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Commit all changes to Settings and close 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_CommitAllChangesToSettingsAndClose() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_CommitAllChangesToSettingsAndClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 DblClick name to edit macro 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_DblClickNameToEditMacro() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_DblClickNameToEditMacro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Delete the selected macro 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_DeleteTheSelectedMacro() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_DeleteTheSelectedMacro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 G-Code to send when the button is clicked. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_GCodeToSendWhenTheButtonIsClicked() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_GCodeToSendWhenTheButtonIsClicked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get me outta here, cancel all changes 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_GetMeOuttaHereCancelAllChanges() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_GetMeOuttaHereCancelAllChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Limit is 5 macros 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_LimitIs5Macros() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_LimitIs5Macros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Name appears on the button, so keep it small 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblGui_UpdateToolTip_NameAppearsOnTheButtonSoKeepItSmall() As String
            Get
                Return ResourceManager.GetString("GrblGui_UpdateToolTip_NameAppearsOnTheButtonSoKeepItSmall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error on close of Grbl port 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblIF_Disconnect_ErrorOnCloseOfGrblPort() As String
            Get
                Return ResourceManager.GetString("GrblIF_Disconnect_ErrorOnCloseOfGrblPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Fatal error on write to Grbl 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblIF_sendData_FatalErrorOnWriteToGrbl() As String
            Get
                Return ResourceManager.GetString("GrblIF_sendData_FatalErrorOnWriteToGrbl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 a accel, mm/sec^2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_AAccelMmSec2() As String
            Get
                Return ResourceManager.GetString("GrblSettings_AAccelMmSec2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  a max rate, mm/min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_AMaxRateMmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_AMaxRateMmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 a max travel, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_AMaxTravelMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_AMaxTravelMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 arc tolerance, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ArcToleranceMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ArcToleranceMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 a, step/mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_AStepMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_AStepMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 dir port invert mask: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_DirPortInvertMask() As String
            Get
                Return ResourceManager.GetString("GrblSettings_DirPortInvertMask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Value 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_FillSettings_Value() As String
            Get
                Return ResourceManager.GetString("GrblSettings_FillSettings_Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 hard limits, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HardLimitsBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HardLimitsBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 homing cycle, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HomingCycleBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HomingCycleBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  homing debounce, msec 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HomingDebounceMsec() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HomingDebounceMsec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 homing dir invert mask 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HomingDirInvertMask() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HomingDirInvertMask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  homing feed, mm/min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HomingFeedMmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HomingFeedMmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 homing pull-off, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HomingPullOffMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HomingPullOffMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 homing seek, mm/min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_HomingSeekMmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_HomingSeekMmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 junction deviation, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_JunctionDeviationMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_JunctionDeviationMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 laser mode 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_LaserMode() As String
            Get
                Return ResourceManager.GetString("GrblSettings_LaserMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  limit pins invert, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_LimitPinsInvertBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_LimitPinsInvertBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 probe pin invert, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ProbePinInvertBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ProbePinInvertBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 report inches, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ReportInchesBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ReportInchesBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 rpm max 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_RpmMax() As String
            Get
                Return ResourceManager.GetString("GrblSettings_RpmMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 rpm min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_RpmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_RpmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 soft limits, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_SoftLimitsBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_SoftLimitsBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 status report mask 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_StatusReportMask() As String
            Get
                Return ResourceManager.GetString("GrblSettings_StatusReportMask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  step enable invert, bool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_StepEnableInvertBool() As String
            Get
                Return ResourceManager.GetString("GrblSettings_StepEnableInvertBool", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 step idle delay, msec 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_StepIdleDelayMsec() As String
            Get
                Return ResourceManager.GetString("GrblSettings_StepIdleDelayMsec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 step port invert mask: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_StepPortInvertMask() As String
            Get
                Return ResourceManager.GetString("GrblSettings_StepPortInvertMask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 step pulse, usec 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_StepPulseUsec() As String
            Get
                Return ResourceManager.GetString("GrblSettings_StepPulseUsec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 x accel, mm/sec^2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_XAccelMmSec2() As String
            Get
                Return ResourceManager.GetString("GrblSettings_XAccelMmSec2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 x max rate, mm/min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_XMaxRateMmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_XMaxRateMmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 x max travel, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_XMaxTravelMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_XMaxTravelMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 x, step/mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_XStepMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_XStepMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 y accel, mm/sec^2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_YAccelMmSec2() As String
            Get
                Return ResourceManager.GetString("GrblSettings_YAccelMmSec2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 y max rate, mm/min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_YMaxRateMmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_YMaxRateMmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 y max travel, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_YMaxTravelMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_YMaxTravelMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 y, step/mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_YStepMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_YStepMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 z accel, mm/sec^2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ZAccelMmSec2() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ZAccelMmSec2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 z max rate, mm/min 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ZMaxRateMmMin() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ZMaxRateMmMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 z max travel, mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ZMaxTravelMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ZMaxTravelMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 z, step/mm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GrblSettings_ZStepMm() As String
            Get
                Return ResourceManager.GetString("GrblSettings_ZStepMm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgFilter_PreFilterMessage_Start() As String
            Get
                Return ResourceManager.GetString("MsgFilter_PreFilterMessage_Start", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
